[package]
name = "pine"
version = "0.2.0"
authors = ["Allen Wild <allenwild93@gmail.com>"]
edition = "2018"

[workspace]
members = ["libarchive"]

[dependencies]
anyhow = "1.0.40"
atty = "0.2.14"
clap = "2.33.3"
libarchive = { path = "./libarchive" }
lscolors = { version = "0.7.1", default-features = false }
termcolor = "1.1.2"
thiserror = "1.0.25"
walkdir = "2.3.2"
